--------------------------------------------------------
--  DDL for Index ACCT_STMT_DATA_STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."ACCT_STMT_DATA_STORE_PK" ON "CSCR_DTB"."ACCT_STMT_DATA_STORE" ("USERID", "UNIQUEID", "SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
