--------------------------------------------------------
--  DDL for Index ARR_BANK_MAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."ARR_BANK_MAS_PK" ON "CSCR_DTB"."ARRANGEMENT_BANK_MASTER" ("ARR_TYPE", "ARR_PROD_TYPE", "BANK_NAME", "ARR_SUB_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
