--------------------------------------------------------
--  DDL for Index ARR_LOC_MAS_PKY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."ARR_LOC_MAS_PKY" ON "CSCR_DTB"."ARRANGEMENT_LOCATION_MASTER" ("ARR_AT", "ARR_TYPE", "BANK_NAME", "LOCATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
