--------------------------------------------------------
--  DDL for Index AT510MB_IDX01
--------------------------------------------------------

  CREATE INDEX "CSCR_DTB"."AT510MB_IDX01" ON "CSCR_DTB"."AT510MB" ("CCN_NO", "AC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
