--------------------------------------------------------
--  DDL for Index BILLER_REFUND_NETOFF_DTLS_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."BILLER_REFUND_NETOFF_DTLS_UK" ON "CSCR_DTB"."BILLER_REFUND_NETOFF_DETAILS" ("FILE_NAME", "REFUND_FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
