--------------------------------------------------------
--  DDL for Index CHQ_SERIES_MASTER_FEED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."CHQ_SERIES_MASTER_FEED_PK" ON "CSCR_DTB"."CHQ_SERIES_MASTER_FEED" ("TB_REF_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
