--------------------------------------------------------
--  DDL for Index OC10T_SEARCH
--------------------------------------------------------

  CREATE INDEX "CSCR_DTB"."OC10T_SEARCH" ON "CSCR_DTB"."OC010TB" ("BR_CD", "POS_CD", "CLG_TYPE", "ZONE_CD", "TXN_DT", "VAL_DT", "FILE_NAME", "REF_NO", "INSTR_TYPE", "BNK_CD", "TXN_CD", "LEGACY_AC", "DRAWER_AC", "MKR_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
