--------------------------------------------------------
--  DDL for Index PK_CA021MB_CI
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_CA021MB_CI" ON "CSCR_DTB"."CA021MB" ("BR_CD", "HUNTING_ACCT", "HUNTED_ACCT", "CHANNEL_ID", "MATURITY_DT", "EFF_DT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
