--------------------------------------------------------
--  DDL for Index PK_CUST_PRDLOC_WB
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_CUST_PRDLOC_WB" ON "CSCR_DTB"."CUST_PROD_LOCATION_WORK" ("UNIT_ID", "PRODUCT_CODE", "LOCATION_CODE", "PRODUCT_TYPE", "CIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
