--------------------------------------------------------
--  DDL for Index PK_CA840PB
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_CA840PB" ON "CSCR_DTB"."CA840PB" ("BR_CD", "MOD_CD", "LANG_CD", "KEY_1", "KEY_2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
