--------------------------------------------------------
--  DDL for Index PK_DE_UPLOAD_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_DE_UPLOAD_DETAIL" ON "CSCR_DTB"."DE_UPLOAD_DETAIL" ("BR_CD", "EXTERNAL_REF_NO", "CURR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
