--------------------------------------------------------
--  DDL for Index PK_LG812HB
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_LG812HB" ON "CSCR_DTB"."LG812HB" ("BR_CD", "LET_CD", "TMP_CD", "VAR_SEQ", "SEQ_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
