--------------------------------------------------------
--  DDL for Index PK_PS028WB
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_PS028WB" ON "CSCR_DTB"."PS028WB" ("BR_CD", "BANK_CD", "MOD_CD", "CCY_CD", "MIRROR_ACC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
