--------------------------------------------------------
--  DDL for Index PK_STATE_CODE_MASTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_STATE_CODE_MASTER" ON "CSCR_DTB"."STATE_CODE_MASTER" ("COUNTRY_ISO_CODE", "STATE_CODE", "UNIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
