--------------------------------------------------------
--  DDL for Index PK_UNIT_MASTE_WB
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PK_UNIT_MASTE_WB" ON "CSCR_DTB"."UNIT_MASTER_WB" ("UNIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
