--------------------------------------------------------
--  DDL for Index PKEY_BATCH_FEED_MAINTENANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PKEY_BATCH_FEED_MAINTENANCE" ON "CSCR_DTB"."BATCH_FEED_MAINTENANCE" ("FEED_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
