--------------------------------------------------------
--  DDL for Index PKY_ECS_USER_NUM_MAINT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."PKY_ECS_USER_NUM_MAINT" ON "CSCR_DTB"."ECS_USER_NUM_MAINT" ("CHANEL_TYPE", "CIF", "ECS_PROD_TYPE", "PROD_PROC", "SPNSR_BANK_NAME_CD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
