--------------------------------------------------------
--  DDL for Index PORTAL_REQUEST_IDX
--------------------------------------------------------

  CREATE INDEX "CSCR_DTB"."PORTAL_REQUEST_IDX" ON "CSCR_DTB"."PORTAL_REQUEST" ("REF_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
