--------------------------------------------------------
--  DDL for Index SCHEDULE_REPORT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSCR_DTB"."SCHEDULE_REPORT_PK1" ON "CSCR_DTB"."SCHEDULE_REPORT_WORK" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
