--------------------------------------------------------
--  DDL for Index TXN_IDXCUSTREF
--------------------------------------------------------

  CREATE INDEX "CSCR_DTB"."TXN_IDXCUSTREF" ON "CSCR_DTB"."TXN_MST_PAY" ("CUSTOMER_REFERENCE_NO", "ACCT_NO_REM", "DEBIT_VALUE_DAT", "FILE_REFERENCE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CSCR_DATA" ;
